version: '3'
services:
  selenoid:
    image: 'aerokube/selenoid'
    network_mode: bridge
    container_name: 'selenoid'
    volumes:
      - './config:/etc/selenoid'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './config/video:/opt/selenoid/video'
      - './config/logs:/opt/selenoid/logs'
    ports:
      - '4444:4444'
  selenoid-ui:
    image: 'aerokube/selenoid-ui'
    network_mode: bridge
    links:
      - selenoid
    container_name: 'selenoid-ui'
    ports:
      - '8080:8080'
    command: ['--selenoid-uri', 'http://192.168.50.45:4444']
    depends_on:
      - selenoid
  tests:
    container_name: 'tests'
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
    - ./allure-report:/app/allure-report
    depends_on:
      - selenoid
      - selenoid-ui

